### ISSUE TITLE
TypeError: fetch is not a function

### ISSUE THREAD

**Issue by KiroFyzu** [ERLANRAHMAT/betabotz-tools#1]
![image](https://github.com/ERLANRAHMAT/betabotz-tools/assets/96397064/26c3daf9-91e6-4721-8755-4d8e141aea67)

**Comment by ERLANRAHMAT** [comment]
![Screenshot_2023_1023_130546](https://github.com/ERLANRAHMAT/betabotz-tools/assets/98427364/e11122d1-0f38-4fee-9b75-247f91ff7a5e)
di baris ke 13 tidak ada fetch 🗿 di bot lain bisa
